package one.papachi.httpd.impl.http;

public enum Http2Setting {

    UNSPECIFIED, HEADER_TABLE_SIZE, ENABLE_PUSH, MAX_CONCURRENT_STREAMS, INITIAL_WINDOW_SIZE, MAX_FRAME_SIZE, MAX_HEADER_LIST_SIZE

}
